- name: Set up Jenkins server on Ubuntu
  hosts: jenkins_server
  become: yes
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  tasks:
    - name: Update apt cache initially
      apt:
        update_cache: yes

    - name: Install Java OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Download and add the Jenkins repository GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Ensure the Jenkins repository is configured
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        line: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
        create: yes

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest
      register: jenkins_install

    - name: Check if Jenkins service is running
      systemd:
        name: jenkins
        state: started
      when: jenkins_install is changed

    - name: Wait for Jenkins to start up
      ansible.builtin.wait_for:
        port: 8080
        timeout: 60
      when: jenkins_install is changed

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
        dest: /tmp/terraform.zip
        mode: '0755'

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Extract Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/terraform

    - name: Install dependencies for Kubernetes apt repository
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Download and add Kubernetes public signing key
      ansible.builtin.shell:
        cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/kubernetes.list
        line: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /'
        create: yes

    - name: Update apt package index after adding Kubernetes repository
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
